INSERT INTO OWNER(OWNERID,FIRSTNAME,LASTNAME) VALUES(1,'Sven','De Smit');
INSERT INTO OWNER(OWNERID,FIRSTNAME,LASTNAME) VALUES(2,'Sabrina','Lambrecht');
INSERT INTO CAR(ID,BRAND,MODEL,COLOR,REGNBR,YEAR,PRICE,DESCR,OWNER) VALUES(1,'Ford','Mustang','Red','ADF-1121',2017,59000,'This is my favourite car',1);
INSERT INTO CAR(ID,BRAND,MODEL,COLOR,REGNBR,YEAR,PRICE,DESCR,OWNER) VALUES(2,'Nissan','Leaf','White','SSJ-3002',2014,29000,'This is an electric car',2);
INSERT INTO CAR(ID,BRAND,MODEL,COLOR,REGNBR,YEAR,PRICE,DESCR,OWNER) VALUES(3,'Toyota','Prius','Silver','KKO-0212',2018,59000,'This is an hybrid car',2);
