
INSERT INTO OWNER(OWNERID,FIRSTNAME,LASTNAME) VALUES(1,'Sven','De Smit');
INSERT INTO OWNER(OWNERID,FIRSTNAME,LASTNAME) VALUES(2,'Sabrina','Lambrecht');
INSERT INTO CAR(BRAND,MODEL,COLOR,REGNBR,YEAR,PRICE,DESCR) VALUES("Ford","Mustang","Red","ADF-1121",2017,59000,"This is my favourite car",1);
INSERT INTO CAR(BRAND,MODEL,COLOR,REGNBR,YEAR,PRICE,DESCR) VALUES("Nissan","Leaf","White","SSJ-3002",2014,29000,"This is an electric car",2);
INSERT INTO CAR(BRAND,MODEL,COLOR,REGNBR,YEAR,PRICE,DESCR) VALUES("Toyota","Prius","Silver","KKO-0212",2018,59000,"This is an hybrid car",2);
