CREATE TABLE CAR(ID INT PRIMARY KEY AUTO_INCREMENT
				,BRAND VARCHAR(255)
				,MODEL VARCHAR(255)
				,COLOR VARCHAR(255)
				,REGNBR VARCHAR(255)
				,DESCR VARCHAR(255)
				,YEAR INT
				,PRICE INT
				,OWNER INT FOREIGN KEY REFERENCES OWNER(OWNERID));

CREATE TABLE OWNER(OWNERID INT PRIMARY KEY AUTO_INCREMENT
				,FIRSTNAME VARCHAR(255)
				,LASTNAME VARCHAR(255));
				